language: generic
sudo: true
# branches:
#     only:
#         - master
addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
before_install:
    # - travis_wait 60 bash ./scripts/build_travis.sh &>/dev/null
    - sudo apt-get install -y cmake build-essential libcgal-dev libeigen3-dev libboost-all-dev
    - pip install --user cpp-coveralls
install:       
    - echo "Now try to build the module"
    - mkdir build 
    - cd build
    - cmake -DCOVERAGE=1 ..
    - make all
script:
    - ./bin/test_gtest
after_success:
    - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*" -e extern
